name: wiki_checker
env:
  LANG: "en_UK.UTF-8"
  LANGUAGE: "en_UK:en"
  LC_ALL: "en_UK.UTF-8"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */3 * * *"

jobs:
  check-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: python -m pip install -r requirements.txt
      - run: |
          sudo locale-gen ${{ env.LANG }}
          sudo update-locale LANG=${{ env.LANG }}
          python run_tests.py --remote
