name: wiki_checker
env:
  LANG: "en_GB.UTF-8"
  LANGUAGE: "en_GB:en"
  LC_ALL: "en_GB.UTF-8"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */3 * * *"

jobs:
  check-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: python -m pip install -r requirements.txt
      - run: |
          sudo apt-get install -y tzdata locales language-pack-en wbritish-insane
          sudo locale-gen ${{ env.LANG }}
          export LANG="en_GB.UTF-8"
          sudo localectl set-locale LANG="en_GB.UTF-8"
          sudo update-locale LANG=${{ env.LANG }}
          locale -a
          python run_tests.py --remote
